import AppKit
@testable import HubrisVoiceApp
import XCTest

@MainActor
final class TransientPasteboardTests: XCTestCase {
  func testPublishesTextAndHistoryExclusionMarkersOnOneItem() throws {
    let pasteboard = NSPasteboard.withUniqueName()
    defer { pasteboard.releaseGlobally() }
    pasteboard.setString("Previous contents", forType: .string)

    XCTAssertTrue(TransientPasteboard.write("Purple submarine seven.", to: pasteboard))

    XCTAssertEqual(pasteboard.pasteboardItems?.count, 1)
    let item = try XCTUnwrap(pasteboard.pasteboardItems?.first)
    XCTAssertEqual(item.string(forType: .string), "Purple submarine seven.")
    XCTAssertNotNil(item.data(forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType")))
    XCTAssertNotNil(item.data(forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")))
  }
}
