import AppKit

@MainActor
enum TransientPasteboard {
  /// Prepare every type before publishing so clipboard observers never see
  /// an unmarked transcript. https://nspasteboard.org/
  static func write(_ text: String, to pasteboard: NSPasteboard) -> Bool {
    let item = NSPasteboardItem()
    guard
      item.setString(text, forType: .string),
      item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType")),
      item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
    else { return false }
    pasteboard.clearContents()
    return pasteboard.writeObjects([item])
  }
}
